test:
  clients:
    default:
      database: firefreeze_test
      hosts:
        - localhost:27017
development:
  clients:
    default:
      database: firefreeze_dev
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
